version: '3.8'
services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:5
    container_name: ${DB_NAME}
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: ${DB_NAME}
    volumes:
      - ./mongo:/data/db
